defaults:
  run: 
    working-directory: aspnet
    
jobs:
  build:
    name: building
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: dotnet restore
      - run: dotnet build
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - run: dotnet test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 